all : helloworld.c 
	gcc helloworld.c -o hello
	gcc variables.c -o variable
	gcc datatypes.c -o dtype
	gcc arrays.c -o array
	gcc staticarray.c -o staticarr
	gcc pointers.c -o pointer
	gcc if_else.c -o if
	gcc nestedloop.c -o nestl
	gcc switchstatements.c -o switch
	gcc strings.c -o str
	gcc struct.c -o struct

test : 