all : helloworld.c variables.c arrays.c staticarray.c
	gcc helloworld.c -o hello
	gcc variables.c -o variable
	gcc datatypes.c -o dtype
	gcc arrays.c -o array
	gcc staticarray.c -o staticarr
	gcc pointers.c -o pointer